Repository codesquad-member-2020/airbnb-13, pull requests merged in 2020-06, with the labels that each got.

#32 [client] 리뷰요청
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Cards/Card/CardLayout/CardLayout.tsx
  client/src/components/Cards/Cards.tsx
  client/src/components/Filters/DateFilter/DateFilter.tsx
  client/src/components/Filters/Filters.tsx
  client/src/components/Filters/GuestFilter/GuestFilter.tsx
  client/src/components/Filters/GuestFilter/GuestFilterWithButton/GuestFilterWithButton.tsx
  client/src/components/Filters/GuestFilter/Row/Row.tsx
  client/src/components/Filters/PriceFilter/PriceFilter.tsx
  client/src/components/Filters/PriceFilter/PriceFilterWithButton/PriceFilterWithButton.tsx
  client/src/components/custom/Button/Button.tsx
  client/src/components/custom/FilterButton/FilterButton.tsx
  client/src/components/custom/Slider/Bars/Bar/Bar.tsx
  client/src/components/custom/Slider/Bars/Bars.tsx
  client/src/components/custom/Slider/PriceInput/PriceInput.tsx
  client/src/components/custom/Slider/Slider.tsx
  client/src/stories/DateFilter.stories.tsx
  client/src/stories/FilterButton.stories.tsx
  client/src/stories/GuestFilter.stories.tsx
  client/src/stories/GuestFilterWithButton.stories.tsx
  client/src/stories/PriceFilter.stories.tsx
  client/src/stories/PriceFilterWithButton.stories.tsx
  client/src/stories/Row.stories.tsx
  client/tsconfig.json
  client/webpack.dev.js
  client/webpack.prod.js
Labels: client review request

#42 [server] 가격 정보 추가
  BE/src/main/java/com/codesquad/airbnb/controller/RoomController.java
  BE/src/main/java/com/codesquad/airbnb/dto/PriceInfo.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomInfo.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomResponse.java
  BE/src/main/java/com/codesquad/airbnb/repository/PriceMapper.java
  BE/src/main/java/com/codesquad/airbnb/repository/RoomDao.java
  BE/src/main/java/com/codesquad/airbnb/service/RoomService.java
  BE/src/test/java/com/codesquad/airbnb/dto/RoomInfoTest.java
Labels: Server

#45 [server] OAuth 로그인 구현
  BE/src/main/java/com/codesquad/airbnb/config/WebConfig.java
  BE/src/main/java/com/codesquad/airbnb/controller/LoginController.java
  BE/src/main/java/com/codesquad/airbnb/dto/GithubToken.java
  BE/src/main/java/com/codesquad/airbnb/dto/User.java
  BE/src/main/java/com/codesquad/airbnb/dto/UserResponse.java
  BE/src/main/java/com/codesquad/airbnb/error/GlobalRestControllerAdvice.java
  BE/src/main/java/com/codesquad/airbnb/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/airbnb/repository/RoomDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/UserDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/RoomMapper.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/UserMapper.java
  BE/src/main/java/com/codesquad/airbnb/service/LoginService.java
  BE/src/main/java/com/codesquad/airbnb/utils/DayCalculator.java
  BE/src/main/java/com/codesquad/airbnb/utils/GithubLogin.java
  BE/src/main/java/com/codesquad/airbnb/utils/JwtUtils.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/codesquad/airbnb/utils/JwtUtilsTest.java
Labels: Server

#47 [server] 리팩토링 이후 배포
  BE/.gitignore
  BE/appspec.yml
  BE/deploy.sh
  BE/src/main/java/com/codesquad/airbnb/config/WebConfig.java
  BE/src/main/java/com/codesquad/airbnb/controller/LoginController.java
  BE/src/main/java/com/codesquad/airbnb/controller/RoomController.java
  BE/src/main/java/com/codesquad/airbnb/controller/UserController.java
  BE/src/main/java/com/codesquad/airbnb/dto/GithubToken.java
  BE/src/main/java/com/codesquad/airbnb/dto/Guest.java
  BE/src/main/java/com/codesquad/airbnb/dto/GuestResponse.java
  BE/src/main/java/com/codesquad/airbnb/dto/Price.java
  BE/src/main/java/com/codesquad/airbnb/dto/PriceInfo.java
  BE/src/main/java/com/codesquad/airbnb/dto/Reservation.java
  BE/src/main/java/com/codesquad/airbnb/dto/ReservationDate.java
  BE/src/main/java/com/codesquad/airbnb/dto/ReservationRequest.java
  BE/src/main/java/com/codesquad/airbnb/dto/ReservationResponse.java
  BE/src/main/java/com/codesquad/airbnb/dto/Room.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomInfo.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomResponse.java
  BE/src/main/java/com/codesquad/airbnb/dto/User.java
  BE/src/main/java/com/codesquad/airbnb/dto/UserResponse.java
  BE/src/main/java/com/codesquad/airbnb/error/GlobalRestControllerAdvice.java
  BE/src/main/java/com/codesquad/airbnb/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/airbnb/repository/ReservationDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/ReservationMapper.java
  BE/src/main/java/com/codesquad/airbnb/repository/RoomDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/RoomRepository.java
  BE/src/main/java/com/codesquad/airbnb/repository/UserDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/PriceMapper.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/RoomMapper.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/UserMapper.java
  BE/src/main/java/com/codesquad/airbnb/service/LoginService.java
  BE/src/main/java/com/codesquad/airbnb/service/RoomService.java
  BE/src/main/java/com/codesquad/airbnb/service/UserService.java
  BE/src/main/java/com/codesquad/airbnb/utils/DayCalculator.java
  BE/src/main/java/com/codesquad/airbnb/utils/GithubLogin.java
  BE/src/main/java/com/codesquad/airbnb/utils/JwtUtils.java
  BE/src/main/resources/application-dev.properties
  BE/src/main/resources/application-prod.properties
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/airbnb/controller/RoomControllerTest.java
  BE/src/test/java/com/codesquad/airbnb/dto/PriceInfoTest.java
  BE/src/test/java/com/codesquad/airbnb/dto/RoomInfoTest.java
  BE/src/test/java/com/codesquad/airbnb/dto/RoomTest.java
  BE/src/test/java/com/codesquad/airbnb/repository/RoomDaoTest.java
  BE/src/test/java/com/codesquad/airbnb/repository/RoomRepositoryTest.java
  BE/src/test/java/com/codesquad/airbnb/service/RoomServiceTest.java
  BE/src/test/java/com/codesquad/airbnb/utils/DayCalculatorTest.java
  BE/src/test/java/com/codesquad/airbnb/utils/JwtUtilsTest.java
Labels: Server

#49 [server] 로그인한 유저 마이페이지 기능 추가
  BE/appspec.yml
  BE/deploy.sh
  BE/src/main/java/com/codesquad/airbnb/controller/RoomController.java
  BE/src/main/java/com/codesquad/airbnb/controller/UserController.java
  BE/src/main/java/com/codesquad/airbnb/dto/Reservation.java
  BE/src/main/java/com/codesquad/airbnb/error/GlobalRestControllerAdvice.java
  BE/src/main/java/com/codesquad/airbnb/error/exception/AlreadyBookedException.java
  BE/src/main/java/com/codesquad/airbnb/error/exception/ReservationInvalidFormException.java
  BE/src/main/java/com/codesquad/airbnb/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/airbnb/repository/RoomDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/ReservationIdMapper.java
  BE/src/main/java/com/codesquad/airbnb/service/LoginService.java
  BE/src/main/java/com/codesquad/airbnb/service/RoomService.java
  BE/src/test/java/com/codesquad/airbnb/controller/UserControllerTest.java
  BE/src/test/java/com/codesquad/airbnb/repository/RoomDaoTest.java
Labels: Server

#53 [client] 로그인 기능 추가
  client/.env.development
  client/.env.production
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Icon/svg/airbnb.svg
  client/src/Icon/svg/github.svg
  client/src/Icon/svg/index.ts
  client/src/Page/MainPage/MainPage.tsx
  client/src/Page/MyPage/MyPage.tsx
  client/src/action/modalAction.ts
  client/src/action/priceAction.ts
  client/src/action/userAction.ts
  client/src/components/Cards/Card/CardDetail/CardDetail.tsx
  client/src/components/Filters/DateFilter/DateFilter.tsx
  client/src/components/Filters/FilterContentWrap.tsx
  client/src/components/Filters/Filters.tsx
  client/src/components/Filters/GuestFilter/GuestFilter.tsx
  client/src/components/Filters/GuestFilter/GuestFilterWithButton/GuestFilterWithButton.tsx
  client/src/components/Filters/PriceFilter/PriceFilter.tsx
  client/src/components/Filters/PriceFilter/PriceFilterWithButton/PriceFilterWithButton.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Modal/AvailableModal.ts
  client/src/components/Modal/Login/Login.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/custom/Slider/Bars/Bar/Bar.tsx
  client/src/components/custom/Slider/Slider.tsx
  client/src/reducer/index.ts
  client/src/reducer/priceReducer.ts
  client/src/reducer/userReducer.ts
  client/src/saga/fetchCardData.ts
  client/src/saga/fetchUserData.ts
  client/src/saga/index.ts
  client/src/stories/DateFilter.stories.tsx
  client/src/stories/PriceFilter.stories.tsx
  client/src/stories/PriceFilterWithButton.stories.tsx
  client/src/stories/Slider.stories.tsx
  client/src/style/theme.tsx
  client/src/util/cookie/cookie.ts
  client/src/util/customHooks/useFocusOutEvent.tsx
Labels: client

#54 [client] 로그인 기능 dev로 merge
  client/.env.development
  client/.env.production
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Icon/svg/airbnb.svg
  client/src/Icon/svg/github.svg
  client/src/Icon/svg/index.ts
  client/src/Page/MainPage/MainPage.tsx
  client/src/Page/MyPage/MyPage.tsx
  client/src/action/modalAction.ts
  client/src/action/priceAction.ts
  client/src/action/userAction.ts
  client/src/components/Cards/Card/CardDetail/CardDetail.tsx
  client/src/components/Filters/DateFilter/DateFilter.tsx
  client/src/components/Filters/FilterContentWrap.tsx
  client/src/components/Filters/Filters.tsx
  client/src/components/Filters/GuestFilter/GuestFilter.tsx
  client/src/components/Filters/GuestFilter/GuestFilterWithButton/GuestFilterWithButton.tsx
  client/src/components/Filters/PriceFilter/PriceFilter.tsx
  client/src/components/Filters/PriceFilter/PriceFilterWithButton/PriceFilterWithButton.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Modal/AvailableModal.ts
  client/src/components/Modal/Login/Login.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/custom/Slider/Bars/Bar/Bar.tsx
  client/src/components/custom/Slider/Slider.tsx
  client/src/reducer/index.ts
  client/src/reducer/priceReducer.ts
  client/src/reducer/userReducer.ts
  client/src/saga/fetchCardData.ts
  client/src/saga/fetchUserData.ts
  client/src/saga/index.ts
  client/src/stories/DateFilter.stories.tsx
  client/src/stories/PriceFilter.stories.tsx
  client/src/stories/PriceFilterWithButton.stories.tsx
  client/src/stories/Slider.stories.tsx
  client/src/style/theme.tsx
  client/src/util/cookie/cookie.ts
  client/src/util/customHooks/useFocusOutEvent.tsx
Labels: client

#55 [client] 배포 환경에서의 login 오류 수정
  client/src/components/Modal/Login/Login.tsx
  client/src/util/cookie/cookie.ts
Labels: client

#56 [server] fix: 리다이렉트 재설정
  BE/src/main/java/com/codesquad/airbnb/controller/RoomController.java
  BE/src/main/java/com/codesquad/airbnb/controller/UserController.java
  BE/src/main/java/com/codesquad/airbnb/dto/ReservationPreviewResponse.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomInfo.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomPrice.java
  BE/src/main/java/com/codesquad/airbnb/repository/RoomDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/RoomPriceMapper.java
  BE/src/main/java/com/codesquad/airbnb/service/RoomService.java
  BE/src/main/java/com/codesquad/airbnb/utils/GithubLogin.java
  BE/src/main/java/com/codesquad/airbnb/utils/PriceCalculator.java
  BE/src/test/java/com/codesquad/airbnb/controller/UserControllerTest.java
Labels: Server

#57 [server] fix: 리다이렉트 재설정
  BE/src/main/java/com/codesquad/airbnb/controller/RoomController.java
  BE/src/main/java/com/codesquad/airbnb/dto/ReservationPreviewResponse.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomInfo.java
  BE/src/main/java/com/codesquad/airbnb/dto/RoomPrice.java
  BE/src/main/java/com/codesquad/airbnb/repository/RoomDao.java
  BE/src/main/java/com/codesquad/airbnb/repository/mapper/RoomPriceMapper.java
  BE/src/main/java/com/codesquad/airbnb/service/RoomService.java
  BE/src/main/java/com/codesquad/airbnb/utils/GithubLogin.java
  BE/src/main/java/com/codesquad/airbnb/utils/PriceCalculator.java
Labels: Server

#59 [client] 마이페이지 기능 dev 로 머지
  client/.env.development
  client/.env.production
  client/src/Page/MyPage/MyPage.tsx
  client/src/Page/MyPage/MyReservation.tsx
  client/src/components/Modal/Reservation/Box/Box.tsx
  client/src/components/Modal/Reservation/Date/Date.tsx
  client/src/components/Modal/Reservation/Guest/Guest.tsx
  client/src/components/Modal/Reservation/Prices/Prices.tsx
  client/src/components/Modal/Reservation/Reservation.tsx
  client/src/reducer/filterReducer.ts
  client/src/util/cookie/cookie.ts
Labels: client

#61 [client] 마이페이지 수정 dev로 머지
  client/src/Page/MyPage/MyPage.tsx
  client/src/Page/MyPage/MyReservation.tsx
  client/src/components/Modal/Reservation/Reservation.tsx
Labels: client

#62 [#50] feature: JWT로 미로그인시 예외처리 기능 추가
  BE/src/main/java/com/codesquad/airbnb/controller/LoginController.java
  BE/src/main/java/com/codesquad/airbnb/controller/RoomController.java
  BE/src/main/java/com/codesquad/airbnb/error/GlobalRestControllerAdvice.java
  BE/src/main/java/com/codesquad/airbnb/error/exception/JWTNotContainException.java
  BE/src/test/java/com/codesquad/airbnb/utils/JwtUtilsTest.java
Labels: Server

#63 [server] 미로그인시 숙소 미리보기 예외처리
  BE/src/main/java/com/codesquad/airbnb/controller/LoginController.java
  BE/src/main/java/com/codesquad/airbnb/controller/RoomController.java
  BE/src/main/java/com/codesquad/airbnb/error/GlobalRestControllerAdvice.java
  BE/src/main/java/com/codesquad/airbnb/error/exception/JWTNotContainException.java
  BE/src/test/java/com/codesquad/airbnb/utils/JwtUtilsTest.java
Labels: Server

#64 [client] 요청하기 데이터 키값 변경
  client/src/components/Modal/Reservation/Reservation.tsx
Labels: client
